[platformio]
default_envs = ota

[env]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  mathieucarbou/ESP Async WebServer@3.0.6
  ESP32Async/AsyncTCP@3.4.10
  madhephaestus/ESP32Servo@3.1.3

lib_ignore =
  Async TCP
  ESPAsyncTCP-esphome
  AsyncTCP_RP2040W

build_flags =
  -Wno-deprecated-declarations

board_build.embed_txtfiles =
  src/index.html

[env:usb]
upload_protocol = esptool
upload_speed = 921600

[env:ota]
upload_protocol = espota
upload_port = 10.85.31.138
upload_flags =
  --port=3232
  --auth=33333333
  --timeout=60